"""initial

Revision ID: e9192f69bfdb
Revises: 
Create Date: 2026-09-03 10:40:06.103149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9192f69bfdb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'USER', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('prompt_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('prompt_body', sa.Text(), nullable=False),
    sa.Column('interval_minutes', sa.Integer(), nullable=False),
    sa.Column('cron_expression', sa.String(length=100), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prompt_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prompt_configs_next_run_at'), ['next_run_at'], unique=False)

    op.create_table('ideas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reference_code', sa.String(length=20), nullable=False),
    sa.Column('prompt_title', sa.String(length=200), nullable=False),
    sa.Column('raw_content', sa.Text(), nullable=False),
    sa.Column('structured_content', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'CONSIDERATION', 'DISCARDED', name='ideastatus'), nullable=False),
    sa.Column('upvotes_count', sa.Integer(), nullable=False),
    sa.Column('downvotes_count', sa.Integer(), nullable=False),
    sa.Column('net_score', sa.Integer(), nullable=False),
    sa.Column('feasibility_score', sa.Float(), nullable=True),
    sa.Column('prompt_config_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['prompt_config_id'], ['prompt_configs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ideas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ideas_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ideas_net_score'), ['net_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_ideas_prompt_config_id'), ['prompt_config_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ideas_reference_code'), ['reference_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_ideas_status'), ['status'], unique=False)

    op.create_table('idea_status_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('idea_id', sa.UUID(), nullable=False),
    sa.Column('changed_by_id', sa.UUID(), nullable=False),
    sa.Column('old_status', sa.Enum('NEW', 'CONSIDERATION', 'DISCARDED', name='ideastatus'), nullable=False),
    sa.Column('new_status', sa.Enum('NEW', 'CONSIDERATION', 'DISCARDED', name='ideastatus'), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['idea_id'], ['ideas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('idea_status_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_idea_status_history_changed_at'), ['changed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_idea_status_history_idea_id'), ['idea_id'], unique=False)

    op.create_table('secondary_action_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('idea_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.Enum('REFINE', 'COMPETITORS', 'FEASIBILITY_SCORE', name='actiontype'), nullable=False),
    sa.Column('model_used', sa.String(length=100), nullable=False),
    sa.Column('result_data', sa.JSON(), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['idea_id'], ['ideas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('secondary_action_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_secondary_action_results_executed_at'), ['executed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_secondary_action_results_idea_id'), ['idea_id'], unique=False)

    op.create_table('votes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('idea_id', sa.UUID(), nullable=False),
    sa.Column('value', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['idea_id'], ['ideas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'idea_id', name='uq_user_idea_vote')
    )
    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_votes_idea_id'), ['idea_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_votes_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_votes_user_id'))
        batch_op.drop_index(batch_op.f('ix_votes_idea_id'))

    op.drop_table('votes')
    with op.batch_alter_table('secondary_action_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_secondary_action_results_idea_id'))
        batch_op.drop_index(batch_op.f('ix_secondary_action_results_executed_at'))

    op.drop_table('secondary_action_results')
    with op.batch_alter_table('idea_status_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_idea_status_history_idea_id'))
        batch_op.drop_index(batch_op.f('ix_idea_status_history_changed_at'))

    op.drop_table('idea_status_history')
    with op.batch_alter_table('ideas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ideas_status'))
        batch_op.drop_index(batch_op.f('ix_ideas_reference_code'))
        batch_op.drop_index(batch_op.f('ix_ideas_prompt_config_id'))
        batch_op.drop_index(batch_op.f('ix_ideas_net_score'))
        batch_op.drop_index(batch_op.f('ix_ideas_created_at'))

    op.drop_table('ideas')
    with op.batch_alter_table('prompt_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prompt_configs_next_run_at'))

    op.drop_table('prompt_configs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
